### ISSUE TITLE
Mix and match between conda and pip is not good

### ISSUE THREAD

**Issue by RamRS** [rghu/reconCNV#1]
I think `conda install` should be used all through, or make it a `pip` thing. Mix and match is not good. Plus, `source [de]activate` is deprecated, it should be `conda deactivate`.

**Comment by RamRS** [comment]
Raghu, the number of requirements on the conda file is fewer than those in the pip file. Is there a difference between how pip and conda operate wrt the dependencies file?

**Comment by rghu** [comment]
I don't think so. Just the creation of the requirements file was a little different in each case. For pip, I used `pip freeze` that lists all modules installed in the environment (including dependencies) to create the requirements file whereas for conda I used `conda env export --from-history` (this installs the dependencies just like pip but does not print them to the requirements file).
